adds CIDR/IP input to censys
projectdiscovery/uncover pull request #129
Opened 2022-12-22 11:50 UTC by tarunKoyalwar

# Description

- allow cidr/ip input to censys

closes #121

2022-12-22 11:50 UTC, tarunKoyalwar commented
```sh
$ ./uncover -q "51.91.110.0/24" -e censys -v                                                              127 ↵

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/ v1.0.1

		projectdiscovery.io

[censys] 51.91.110.0:21
[censys] 51.91.110.0:22
[censys] 51.91.110.0:80
[censys] 51.91.110.0:123
[censys] 51.91.110.0:80
[censys] 51.91.110.2:21
[censys] 51.91.110.2:22
[censys] 51.91.110.2:25
[censys] 51.91.110.2:53
[censys] 51.91.110.2:80
....
```

2022-12-26 05:32 UTC, ehsandeep requested changes
@tarunKoyalwar this is a generic issue with any engine and not specific to censys, and I assume this happens because of automatic handling of IP/CIDR input o auto-select `shodan-idb` as an engine to use, since this causing an issue, we can remove this auto handling behavior and treat `shodan-idb` as other engines, i.e can be used when specified.

2022-12-27 14:31 UTC, tarunKoyalwar commented
# Updated Changes

- Removes Agent Whitelisting based on input type
- Removes `shodan-idb` from default engines list
- fix `Unexpected EOF` caused due to improper closing of connections (closes #130)


![uncover_shodan](https://user-images.githubusercontent.com/45962551/209680930-3eb1e6bc-97a8-43f0-92cc-fdd2e3ae3e0c.png)

2022-12-27 17:02 UTC, ehsandeep approved these changes

2022-12-27 17:02 UTC, merged