hunter.how - new api provider support
projectdiscovery/uncover pull request #166
Opened 2023-02-28 19:43 UTC by xm1k3

2023-03-01 14:37 UTC, Mzack9999 requested changes
- [x] Please update the readme with newly added sources (including publicwww)
- [x] Could you provide an example query, I'm getting no results with a valid token and
```console
$ go run . -q test -e hunterhow

```

2023-03-01 15:41 UTC, xm1k3 commented
```
./uncover -e hunterhow -q 'product.name="jira"' -f host -v  

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/ v1.0.2

                projectdiscovery.io

[hunterhow] community.deiser.com
[hunterhow] jira.deiser.com
[hunterhow] retchat.com
[hunterhow] www.retchat.com
[hunterhow] www.rico-baby.com
[hunterhow] ip74.ip-79-137-122.eu
[hunterhow] team.gitee.cn
```

2023-03-02 07:53 UTC, Mzack9999 approved these changes
lgtm

```console
$ go run . -e hunterhow -q 'product.name=\"jira\"' -f host -v  
...
[hunterhow] dev.proaimltd.com.cn
[hunterhow] build.bmb1688.com
```

2023-03-03 06:13 UTC, tarunKoyalwar commented on runner/options.go
> +		len(options.HunterHow) == 0 {
@xm1k3 , I think we can use newly added generic comparison helper function here https://github.com/projectdiscovery/utils/issues/90

Ex:
```go
genericutils.EqualsAll(0,len(options.ZoomEye),len(options.Netlas))
```

2023-03-03 06:33 UTC, tarunKoyalwar commented on uncover/agent/hunterhow/hunterhow.go
> +
@xm1k3 ,not sure if you want to implement in this PR or a new one . but just to point out this implementation looks good if no of results < 1000 (10 requests are made in serial) but if there are more than 1000> requests it takes time which shouldn't be the case . 
From api docs  it returns ` "total":5994` in response so after first request we can get total results and calculate number of pages available and fetch them according to `limit` cli option in parallel, this way it won't take that much time 

```
so query returns 5994 results it is ~60 req 
60 req in serial (current implementation) takes ~40-50 sec 
60 req in parallel takes ~10 sec
*estimated time here is approx and depends on various factors
```

2023-03-03 06:35 UTC, tarunKoyalwar approved these changes
lgtm ! suggested some possible optimizations
```console
$ ./uncover -hh "product.name=\"jira\"" -f host -v

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/ v1.0.2

		projectdiscovery.io

[hunterhow] gentlecode.com
[hunterhow] www.gentlecode.com
[hunterhow] host64.ru
[hunterhow] jira.erbanyy.com
[hunterhow] jira.ptponclick.com

```

2023-03-03 22:44 UTC, ehsandeep approved these changes

2023-03-03 22:44 UTC, merged