code refactoring to provide abstracted library
projectdiscovery/uncover pull request #182
Opened 2023-03-20 23:35 UTC by xm1k3

2023-03-29 13:19 UTC, tarunKoyalwar commented
```console
$ go run . -s "ssl:'hackerone.com'" -v

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

		projectdiscovery.io

[INF] Current uncover version v1.0.3 (latest)
[shodan] 2606:4700::6810:6434:2083
[shodan] 104.16.100.52:8443
[shodan] 104.16.99.52:8443
[shodan] 2606:4700::6810:6434:2087
[shodan] 2606:4700::6810:6334:443
[shodan] 2606:4700::6810:6334:8443
[shodan] 2606:4700::6810:6334:2087
[shodan] 104.16.99.52:2083
[shodan] 104.16.99.52:443
[shodan] 104.16.100.52:443
[shodan] 104.16.100.52:2083
[shodan] 2606:4700::6810:6434:8443
[shodan] 2606:4700::6810:6434:443
[shodan] 2606:4700::6810:6334:2083
[shodan] 164.92.231.194:443
```

2023-03-29 13:36 UTC, tarunKoyalwar commented
### Integration / Library Code

- Now uncover is completely abstracted i.e logic/code does not need to be changed downstream (nuclei etc) if we add new/sources 

https://github.com/projectdiscovery/uncover/blob/99e091ac33f65bc490ca33a87c226d977561f7ca/examples/main.go#L1-L36

2023-03-29 13:54 UTC, tarunKoyalwar commented
### Follow up Issue

- replace https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/protocols/common/uncover/uncover.go with ^

2023-03-29 15:55 UTC, Mzack9999 requested changes
Implementation: lgtm
Notes:
- suggesting minor optional refactor
- I think we should make it clear in the readme that now the runner is not reusable anymore with different queries, but a new instance needs to be created with new options

2023-03-29 15:55 UTC, Mzack9999 commented on runner/options.go
> +func appendAllQueries(options *Options) {
What do you think about the following:
```go
func appendQuery(options *Options, name string, queries ...string) {
	if len(queries) > 0 {
		options.Engine = append(options.Engine, name)
		options.Query = append(options.Query, queries...)
	}
}

func appendAllQueries(options *Options) {
	appendQuery(options, "shodan", options.Shodan...)
...
}
```

2023-03-29 15:55 UTC, Mzack9999 commented on runner/runner.go
> +
remove new line

2023-03-30 18:21 UTC, Mzack9999 approved these changes
lgtm

2023-04-02 20:43 UTC, ehsandeep requested changes
This works

```
echo jira | ./uncover -v
```

but not this:

```
echo jira | ./uncover
```

2023-04-11 07:41 UTC, tarunKoyalwar commented
```console
$ ./uncover -q "ssl:hackerone.com" -e shodan  -v

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

		projectdiscovery.io

[INF] Current uncover version v1.0.4-dev (dev)
[shodan] 104.16.100.52:443
[shodan] 104.16.99.52:2083
[shodan] 104.16.100.52:2083
[shodan] 2606:4700::6810:6434:8443
[shodan] 2606:4700::6810:6434:2083
[shodan] 104.16.99.52:8443
[shodan] 104.16.100.52:8443
[shodan] 2606:4700::6810:6434:443
[shodan] 2606:4700::6810:6334:2083
[shodan] 2606:4700::6810:6334:443
[shodan] 104.16.99.52:443
[shodan] 2606:4700::6810:6334:8443
[shodan] 164.92.231.194:443
```
```console
$ ./uncover -q "ssl:hackerone.com" -e shodan 

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

		projectdiscovery.io

[INF] Current uncover version v1.0.4-dev (dev)
104.16.100.52:443
104.16.99.52:2083
104.16.100.52:2083
2606:4700::6810:6434:8443
2606:4700::6810:6434:2083
104.16.99.52:8443
104.16.100.52:8443
2606:4700::6810:6434:443
2606:4700::6810:6334:2083
2606:4700::6810:6334:443
104.16.99.52:443
2606:4700::6810:6334:8443
164.92.231.194:443
```

2023-04-11 13:15 UTC, ehsandeep approved these changes

2023-04-11 13:15 UTC, merged