show raw or json output on default run
projectdiscovery/uncover pull request #235
Opened 2023-06-05 10:10 UTC by RamanaReddy0M

2023-06-05 10:16 UTC, RamanaReddy0M commented
```console
./uncover -q element -j

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.5 (latest)
{"timestamp":1685960122,"source":"shodan","ip":"54.95.12.151","port":50000,"host":"ec2-54-95-12-151.ap-northeast-1.compute.amazonaws.com","url":""}
{"timestamp":1685960122,"source":"shodan","ip":"139.224.210.115","port":8649,"host":"","url":""}
{"timestamp":1685960122,"source":"shodan","ip":"65.109.234.163","port":443,"host":"static.163.234.109.65.clients.your-server.de","url":""}
...
```

2023-06-05 11:16 UTC, ehsandeep requested changes
@RamanaReddy0M can we also include a tests for this as this is a regression issue.

2023-06-26 13:31 UTC, tarunKoyalwar approved these changes
lgtm !

```console
./uncover -r -q element

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

		projectdiscovery.io

[INF] Current uncover version v1.0.5 (latest)
{"_shodan":{"crawler":"42f86247b760542c0192b61c60405edc5db01d55","id":"28efde00-d1c9-46f0-9d33-ef2ef234173c","module":"https","options":{},"ptr":true,"region":"eu"},"asn":"AS3269","data":"\u003c!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\u003e\r\n\u003chtml\u003e\r\n\u003chead\u003e\r\n\u003cmeta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" /\u003e\r\n\u003ctitle\u003e\u003c/title\u003e\r\n\u003cstyle type=\"text/css\"\u003e\r\n\u003c!--\r\n.container {\r\n\twidth: 0%\r\n    height: 0px;\r\n    text-align: center;  /* align the inline(-block) elements horizontally */\r\n    font: 0/0 a;         /* remove the gap between inline(-block) elements */\r\n\tbackground-color:#FFFFFF;\r\n}\r\n\r\n.container:before {    /* create a full-height inline block pseudo=element */\r\n    content: ' ';\r\n    display: inline-block;\r\n    vertical-align: middle;  /* vertical alignment of the inline element */\r\n    height: 100%;\r\n}\r\n\r\n#element {\r\n    display: inline-block;\r\n    vertical-align: middle;  /* vertical alignment of the inline element */\r\n    font: 16px/1 Arial sans-serif;        /* \u003c-- reset the font property */\r\n}\r\n\r\n--\u003e\r\n\u003c/style\u003e\r\n\u003c/head\u003e\r\n\u003cbody\u003e\r\n\u003cdiv id=\"container\"\u003e\u003cdiv class=\"container\"\u003e\r\n\u003cdiv id=\"element\"\u003e\r\n\u003cimg src=\"https://costruzione.health4id.it/costruzione.jpg\" /\u003e\r\n\u
```

2023-08-28 19:00 UTC, ehsandeep approved these changes

2023-08-28 19:00 UTC, merged