Improve error handling and efficiency in Result methods
projectdiscovery/uncover pull request #413
Opened 2024-02-18 20:01 UTC by dante-tech

This commit introduces several enhancements to the Result struct methods in our Go application, focusing on error handling, efficiency, and code readability.

## Changes made:
- Modified the JSON() method to return an error alongside the JSON string. This change ensures that any issues encountered during the marshalling process are not silently ignored, allowing callers to handle errors appropriately.
- Replaced `fmt.Sprint` with `strconv.Itoa` for integer-to-string conversion in the IpPort() and HostPort() methods. This adjustment improves the efficiency of these methods by avoiding the reflection-based operations of `fmt`.
- Encapsulated the error field within the Result struct by making it unexported. This design decision restricts access to the error field, promoting the use of methods for error handling and thus enhancing data encapsulation.
- Added an Error() method to provide controlled access to the Result's error field, allowing external packages to handle errors in a structured manner.

These improvements aim to enhance the maintainability, performance, and reliability of our application, ensuring better error handling and data processing efficiency.

2024-02-19 14:47 UTC, olearycrew commented
Thanks for this contribution @dante-tech

2024-02-19 19:39 UTC, dante-tech commented
No problem @olearycrew! I'm very glad to help!

2024-05-05 14:14 UTC, ehsandeep requested changes
Hi @dante-tech, apologies for late response, can you please take a look at build fail / error.

2024-05-05 15:47 UTC, dante-tech commented
Hey @ehsandeep thank you to have taken the time to review this PR. I refactored the code a bit, hoping it will work now!

Please contact me anytime!

2024-05-06 07:34 UTC, dogancanbakir requested changes

2024-05-06 07:34 UTC, dogancanbakir commented on sources/result.go
> +// Could also be removed
Let's remove this -I don't think we need this.

2024-05-06 07:34 UTC, dogancanbakir commented on sources/result.go
> +package result
duplicate pkg definition

2025-02-05 06:29 UTC, closed without merging