Fix verbose output
projectdiscovery/uncover pull request #73
Opened 2022-09-04 13:47 UTC by edoardottt

Why does uncover print two times the output when in verbose mode?

Example:  
uncover v0.0.7  
Before PR
```
[shodan] 50.17.31.108:80
50.17.31.108:80
[shodan] 170.82.16.201:8086
170.82.16.201:8086
[shodan] 35.228.207.232:80
35.228.207.232:80
[shodan] 119.82.224.49:8086
119.82.224.49:8086
[shodan] 147.75.105.59:8081
147.75.105.59:8081
[shodan] 34.68.216.251:80
34.68.216.251:80
[shodan] 104.211.216.23:3000
104.211.216.23:3000
[shodan] 139.180.165.175:3000
139.180.165.175:3000
```

After PR:
```
[shodan] 50.17.31.108:80
[shodan] 170.82.16.201:8086
[shodan] 35.228.207.232:80
[shodan] 119.82.224.49:8086
[shodan] 147.75.105.59:8081
[shodan] 34.68.216.251:80
[shodan] 104.211.216.23:3000
[shodan] 139.180.165.175:3000
```

2022-09-04 15:09 UTC, ehsandeep reviewed
@edoardottt thank you for the fix, probably it was being used to write output file and stdout; although we can ignore printing it out to stdout when verbose mode is used, but we need to support file write when `-o` flag is used, which is currently not working after the change.

2022-09-04 17:06 UTC, edoardottt commented
Understood. 
This is the least bulky code I can think of in order to preserve a good verbose output (kinda obsessed with that) and file output.  
Just close the PR if it adds too much complexity

2022-09-04 20:49 UTC, ehsandeep approved these changes
```console

echo jira | ./uncover -v

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/ v0.0.7

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using uncover, you also agree to the terms of the APIs used.

[WRN] only ip/cidr are accepted
[shodan] 43.130.66.10:1925
[shodan] 34.209.22.129:443
[shodan] 193.41.223.18:80
[shodan] 44.226.111.117:443
[shodan] 20.101.121.11:80
[shodan] 52.24.184.224:443
[shodan] 117.48.120.226:37215
[shodan] 162.55.39.153:443
[shodan] 85.235.66.22:443
[shodan] 13.95.16.10:80
[shodan] 213.240.174.174:443
[shodan] 13.70.38.92:443
[shodan] 18.138.191.115:11000
[shodan] 52.208.44.95:80
[shodan] 117.48.120.226:143
[shodan] 77.223.100.88:443
[shodan] 13.37.153.39:443
[shodan] 3.223.92.9:80
[shodan] 18.138.191.115:5986
[shodan] 43.130.64.95:3111
```

2022-09-05 08:19 UTC, Mzack9999 requested changes

2022-09-05 08:19 UTC, Mzack9999 commented on runner/runner.go
> +	writerName := "stdout"
I think we can declare the strings as constants:
```go
const (
	stdoutWriterName = "stdout"
	fileWriterName   = "file"
)
```

2022-09-05 08:19 UTC, Mzack9999 commented on runner/output_writer.go
> +func (o *OutputWriter) WriteString(data string, name string) {
It's only a matter of style, but I think that `name` should be the first argument unless you want to make the function variadic (eg. `WriteString(data string, names ...string)`)

2022-09-05 08:19 UTC, Mzack9999 commented on runner/output_writer.go
> +func (o *OutputWriter) Write(data []byte, name string) {
Same as `WriteString` function

2022-09-05 08:19 UTC, Mzack9999 commented on runner/output_writer.go
> +func (o *OutputWriter) WriteJsonData(data uncover.Result, name string) {
Same as `WriteString` function

2022-09-06 08:05 UTC, Mzack9999 approved these changes

2022-09-06 09:01 UTC, merged